# change the followings to match your Github username and repo name
baseurl: "/jmyang" # the name of your github repo
url: "https://bobandjeffarefarmers.github.io/jmyang/" # the url of your github pages

# site information used in page title, meta data etc.
title: "Jonathan Yang Personal Website"
description: Jonathan's Website

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Jonathan Yang
author-bio: student | investor  # change to false to hide
author-image: IMG_3861.JPG  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: false
facebook: false
instagram: https://www.instagram.com/jonyang.3011/
github: https://github.com/BoBandJeFFarefarmers
linkedin: <script src="https://platform.linkedin.com/badges/js/profile.js" async defer type="text/javascript"></script>
          <div class="badge-base LI-profile-badge" data-locale="en_US" data-size="medium" data-theme="dark" data-type="VERTICAL" data-vanity="jonathan-yang-4abb0b287" data-version="v1"><a class="badge-base__link LI-simple-link" href="https://www.linkedin.com/in/jonathan-yang-4abb0b287?trk=profile-badge">Jonathan Yang</a></div>
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
